# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Destination.create({name: "Mars", banner_image_url: "banner-mars.jpg", description: "Mars is the fourth planet from the Sun and the second smallest planet in the Solar System, after Mercury. Named after the Roman god of war, it is often referred to as the 'Red Planet' because the iron oxide prevalent on its surface gives it a reddish appearance. Mars is a terrestrial planet with a thin atmosphere, having surface features reminiscent both of the impact craters of the Moon and the valleys, deserts, and polar ice caps of Earth."})
Destination.create({name: "Venus", banner_image_url: "banner-venus.jpg", description: "Venus is the second planet from the Sun, orbiting it every 224.7 Earth days. It has the longest rotation period (245 days) of any planet in the Solar System, and, unusually, rotates in the opposite direction to most other planets. It has no natural satellite. It is named after the Roman goddess of love and beauty."})
Destination.create({name: "Pluto", banner_image_url: "banner-pluto.jpg", description: "Pluto is a dwarf planet in the Kuiper belt, a ring of bodies beyond Neptune. It was the first Kuiper belt object to be discovered. It is the largest and second-most-massive known dwarf planet in the Solar System and the ninth-largest and tenth-most-massive known object directly orbiting the Sun. Like other Kuiper belt objects, Pluto is primarily made of ice and rock and is relatively small—about one-sixth the mass of Earth's Moon and one-third its volume."})
Destination.create({name: "Saturn", banner_image_url: "banner-saturn.jpg", description: "Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius about nine times that of Earth. Although only one-eighth the average density of Earth, with its larger volume Saturn is just over 95 times more massive. Saturn is named after the Roman god of agriculture."})
Destination.create({name: "Uranus", banner_image_url: "banner-uranus.jpg", description: "Uranus is the seventh planet from the Sun. It has the third-largest planetary radius and fourth-largest planetary mass in the Solar System. Uranus's atmosphere, although similar to Jupiter's and Saturn's in its primary composition of hydrogen and helium, contains more 'ices', such as water, ammonia, and methane, along with traces of other hydrocarbons. It is the coldest planetary atmosphere in the Solar System. The interior of Uranus is mainly composed of ices and rock."})
Destination.create({name: "Mercury", banner_image_url: "banner-mercury.jpg", description: "Mercury is the smallest planet in the Solar System and the one closest to the Sun, with an orbital period of about 88 Earth days, which is much faster than any other planet in the Solar System. Seen from Earth, it appears to move around its orbit in about 116 days. It has no known natural satellites. It is named after the Roman deity Mercury, the messenger to the gods."})
Destination.create({name: "Earth", banner_image_url: "banner-earth.jpg", description: "Earth is the third planet from the Sun, the densest planet in the Solar System, the largest of the Solar System's four terrestrial planets, and the only astronomical object known to harbor life. 71% of Earth's surface is covered with water, with the remainder consisting of continents and islands"})
Destination.create({name: "Jupiter", banner_image_url: "banner-jupiter.jpg", description: "Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a giant planet with a mass one-thousandth that of the Sun, but two and a half times that of all the other planets in the Solar System combined. Jupiter is a gas giant, along with Saturn. (Uranus and Neptune are ice giants.) Jupiter was known to astronomers of ancient times. The Romans named it after their god Jupiter."})
Destination.create({name: "Neptune", banner_image_url: "banner-neptune.jpg", description: "Neptune is the eighth and farthest known planet from the Sun in the Solar System. It is the fourth-largest planet by diameter and the third-largest by mass. Among the giant planets in the Solar System, Neptune is the most dense. Neptune is 17 times the mass of Earth and is slightly more massive than its near-twin Uranus, which is 15 times the mass of Earth and slightly larger than Neptune. Neptune is named after the Roman god of the sea."})
User.create({username: "mcarter", password: "password", email: "matt@example.com", avatar_url: "av-image.jpg", about_me: "Hi! I'm Matt, I love space!"})
User.create({username: "thepicard", password: "password", email: "picard@example.com", avatar_url: "avatar-picard.jpg", about_me: "Captain Jean Luc Picard of the starship Enterprise. Flautist."})
User.create({username: "potatolovr", password: "password", email: "mark.watney@nasa.gov", avatar_url: "avatar-watney.png", about_me: "Astronaut, Botanist, Survivalist, Sciencer of shit."})
User.create({username: "heywilly", password: "password", email: "alf@example.com", avatar_url: "avatar-alf.jpg", about_me: "Originally from Melmac...do you have any cats? I kill me! HAAA!!"})
User.create({username: "wascawywabbit", password: "password", email: "bugs@example.com", avatar_url: "avatar-bugs.jpg", about_me: "What's up, Doc? I love humiliating idiot hunters, frustrating cranky ducks, and shooting hoops in spaaaaaace!"})
